name: "MyCustomRecipe"
version: 1.1
author: Joe2357
description: "Using only my wild survival, make my custom item"

main: mycustomrecipe.Main

commands:
    recipeReload:
        description: "Reload custom recipe"